greenhouse_geometry:
  lane_offset: 1.2
  num_rows: 3
  p1_end:
  - 3.436133645200154
  - 0.6983551208577037
  p1_start:
  - -3.5955527202599673
  - 0.41841733743905035
  row_separation: 3.1910158026434097
  step_distance: 0.5
