# Ruta Generada Autom√°ticamente
poses:
  - header:
      frame_id: map
    pose:
      position:
        x: -5.2700
        y: -2.6500
        z: 0.0
      orientation:
        x: 0.0000
        y: 0.0000
        z: 0.0000
        w: 1.0000
  - header:
      frame_id: map
    pose:
      position:
        x: 5.1300
        y: -2.6500
        z: 0.0
      orientation:
        x: 0.0000
        y: 0.0000
        z: 0.0000
        w: 1.0000
  - header:
      frame_id: map
    pose:
      position:
        x: 5.1300
        y: 9.7000
        z: 0.0
      orientation:
        x: 0.0000
        y: 0.0000
        z: 1.0000
        w: 0.0000
  - header:
      frame_id: map
    pose:
      position:
        x: -5.2700
        y: 9.7000
        z: 0.0
      orientation:
        x: 0.0000
        y: 0.0000
        z: 1.0000
        w: 0.0000
