- name: Punto_0
  x: -2.75
  y: 7.57
  yaw: -41.877869537884294
- name: Punto_1
  x: -1.2999999999999998
  y: 6.27
  yaw: -3.7429882956871343
- name: Punto_2
  x: 4.05
  y: 5.92
  yaw: 66.80140948635182
- name: Punto_3
  x: 4.500000000000001
  y: 6.970000000000001
  yaw: 168.43986920578223
- name: Punto_4
  x: 0.10000000000000053
  y: 7.870000000000001
  yaw: -173.92754359279232
- name: Punto_5
  x: -2.2499999999999996
  y: 7.620000000000001
  yaw: -174.28940686250036
- name: Punto_6
  x: -2.75
  y: 7.57
  yaw: -100.56101069119639
- name: Punto_7
  x: -3.3
  y: 4.620000000000001
  yaw: -40.155999624919325
- name: Punto_8
  x: -1.6999999999999997
  y: 3.27
  yaw: -6.398956627368915
- name: Punto_9
  x: 3.6500000000000004
  y: 2.6700000000000004
  yaw: 74.9315118405078
- name: Punto_10
  x: 4.000000000000001
  y: 3.97
  yaw: 169.11447294534128
- name: Punto_11
  x: -1.1999999999999997
  y: 4.970000000000001
  yaw: -170.53767779197437
- name: Punto_12
  x: -3.3
  y: 4.620000000000001
  yaw: -96.6544250460066
- name: Punto_13
  x: -3.65
  y: 1.62
  yaw: -39.80557109226519
- name: Punto_14
  x: -2.15
  y: 0.3700000000000001
  yaw: -10.06068979532297
- name: Punto_15
  x: 0.9500000000000002
  y: -0.17999999999999972
  yaw: -1.273030020056711
- name: Punto_16
  x: 3.2
  y: -0.22999999999999998
  yaw: 91.73570458892839
- name: Punto_17
  x: 3.1500000000000004
  y: 1.4200000000000004
  yaw: 175.0062560141766
- name: Punto_18
  x: -1.9999999999999996
  y: 1.8700000000000006
  yaw: -170.13419305691565
- name: Punto_19
  x: -3.1499999999999995
  y: 1.6700000000000004
  yaw: -174.28940686250036
- name: Punto_20
  x: -3.65
  y: 1.62
  yaw: 0.0
